services:
    sgk_barcode.generator:
        class: SGK\BarcodeBundle\Generator\Generator

    sgk_barcode.twig.extension:
        class: SGK\BarcodeBundle\Twig\Extensions\Barcode
        arguments:
            - @sgk_barcode.generator
        tags:
            - { name: twig.extension }
